package ibis.mbf.client.gui;

import java.util.EventObject;

public class ClientWindowEvent extends EventObject {

    // Generated by eclipse
    private static final long serialVersionUID = 3954092147713907887L;

    private final String fileName;

	public ClientWindowEvent(Object source, String fileName) {
		super(source);
		this.fileName = fileName;
	}

	public String getFileName() {
		return fileName;
	}
}
