package ibis.mbf.client.gui;

import java.util.EventObject;

public class ConnectComponentEvent extends EventObject {

    // Generated by eclipse
    private static final long serialVersionUID = 6195764491998122741L;
    
    private final String command;

    public ConnectComponentEvent(Object source, String command) {
		super(source);
		this.command = command;
	}

    public String getCommand() {
		return command;
	}
}
