package ibis.mbf.client.gui;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.image.BufferedImage;

import javax.swing.JPanel;

public class MediaPanel extends JPanel {

    // Generated by eclipse
    private static final long serialVersionUID = 8029502015844661379L;
    
    public static final int	PANEL_WIDTH  = 320;
	public static final int	PANEL_HEIGHT = 240;

	private BufferedImage	img;

	public MediaPanel() {
		img = new BufferedImage(PANEL_WIDTH, PANEL_HEIGHT,
								BufferedImage.TYPE_INT_RGB);
	}

	public void setMediaFrame(BufferedImage img) {
		this.img = img;
		repaint();
	}

	public void paint(Graphics g) {
		g.setColor(Color.black);
		g.fillRect(0, 0, PANEL_WIDTH, PANEL_HEIGHT);
		g.drawImage(img, 0, 0, this);
	}

	public Dimension getPreferredSize() {
		return new Dimension(PANEL_WIDTH, PANEL_HEIGHT);
	}
}
