package ibis.dog;

import java.io.Serializable;

public class FeatureVector implements Serializable {
   
    // Generated by eclipse
    private static final long serialVersionUID = -5273998909448194335L;
    
    private final int invariants;
    
    private final int receptiveFields;
    
    private final double [] vector;
    
    public FeatureVector(int invariants, int receptiveFields) { 
        this.invariants = invariants;
        this.receptiveFields = receptiveFields;
        vector = new double[invariants*receptiveFields*2];
    }
    
    public double[] getVector() {
        return vector;
    }
    
    public int getInvariants() {
        return invariants;
    }

    public int getReceptiveFields() {
        return receptiveFields;
    }

}
