package ibis.dog.shared;

import java.io.Serializable;

public class Reply implements Serializable {
    // Generated by eclipse
    private static final long serialVersionUID = -6459547406084891300L;

    public byte operation;

    public long sequenceNumber;

    public ServerDescription server;

    public Object result;

    public int id;

    public Reply(ServerDescription server, long sequenceNumber, int id,
            byte operation, Object result) {
        this.server = server;
        this.operation = operation;
        this.id = id;
        this.sequenceNumber = sequenceNumber;
        this.result = result;
    }
}