package ibis.dog.shared;

import java.io.Serializable;

public class RGB32Image implements BaseImage, Serializable {

    // Generated by eclipse
    private static final long serialVersionUID = -5136719712051715163L;

    public final int width;

    public final int height;

    public final int[] pixels;

    public RGB32Image(int width, int height) {
        this.width = width;
        this.height = height;
        pixels = new int[width * height];
    }

    public RGB32Image(int width, int height, int[] image) {
        this.width = width;
        this.height = height;
        this.pixels = image;
    }

    public RGB24Image toRGB24() {
        byte[] bytes = new byte[pixels.length * 3];
        for (int i = 0; i < pixels.length; i++) {
            bytes[i * 3 + 0] = (byte) ((pixels[i] & 0x00FF0000) >> 16);
            bytes[i * 3 + 1] = (byte) ((pixels[i] & 0x0000FF00) >> 8);
            bytes[i * 3 + 2] = (byte) ((pixels[i] & 0x000000FF));
        }
        return new RGB24Image(width, height, bytes);
    }
}
