package ibis.dog.shared;

public class ServerDescription extends MachineDescription {

    // Generated by eclipse
    private static final long serialVersionUID = -1425751845250064011L;
    
    private final String name;
    
    public ServerDescription(MachineDescription md, String name) { 
        super(md);
        this.name = name;
    }
    
    public String getName() { 
        return name;
    }
    
    public String toString() { 
        return name;
    }
    
    public boolean equals(Object o) {

        if (!(o instanceof ServerDescription)) {
            return false;
        }

        ServerDescription other = (ServerDescription) o;

        if (receiveID != null) {
            if (other.receiveID != null) {
                return receiveID.equals(other.receiveID);
            } else {
                return receiveID.ibisIdentifier().equals(other.ibisID)
                        && receiveID.name().equals(other.port);
            }
        } else {
            if (other.receiveID != null) {
                return ibisID.equals(other.receiveID.ibisIdentifier())
                        && port.equals(other.receiveID.name());
            } else {
                return ibisID.equals(other.ibisID) && port.equals(other.port);
            }
        }
    }

}
