package ibis.dog.shared;

import java.io.Serializable;

public class YUV422SPImage implements Serializable {

    // Generated by eclipse
    private static final long serialVersionUID = -3513891213723981644L;

    public final int width;

    public final int height;

    public final byte[] pixels;

    public YUV422SPImage(int width, int height) {
        this.width = width;
        this.height = height;
        // YUV422SP uses 2 bytes per pixel
        pixels = new byte[width * height * 2];
    }

    public YUV422SPImage(int width, int height, byte[] image) {
        this.width = width;
        this.height = height;
        this.pixels = image;
    }
}
