package ibis.mbf.shared;

import ibis.ipl.ReceivePortIdentifier;

public class ClientDescription extends MachineDescription {

    // generated by eclipse
    private static final long serialVersionUID = 1239985468038227089L;

    // TODO: add more fields ?
    public ClientDescription(ReceivePortIdentifier id) { 
        super(id);
    }
}
